#pragma once

#include "mdl_api.h"

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace datayes {
namespace mdl {
namespace mock {

// The mock keeps prices as integer thousandths internally.  Individual MDL
// payload builders convert that value to the exact decimal placement declared
// by the SDK type (for example SZ v2 snapshots use MDLDoubleT<6>).
struct Instrument {
    uint8_t service_id = MDLSID_UNDEFINED;
    std::string security_id;
    int64_t reference_price_milli = 0;
    int64_t tick_size_milli = 10;
    uint32_t lot_size = 1;
    bool option = false;
};

enum class ClockMode {
    // Event time is local wall-clock time minus a small randomized lag.
    Realtime,
    // A deterministic 09:30-11:30, 13:00-15:00 clock.  The clock advances by
    // randomized millisecond steps and skips the midday break.
    SimulatedTradingDay
};

enum class BackpressurePolicy {
    // Slow thread-safe callbacks apply backpressure to the generator.
    Block,
    // Keep the generator moving and count callbacks rejected by a full queue.
    DropNewest
};

struct Config {
    uint64_t seed = 0x4c32464c4f57ULL;
    // Zero means unpaced/as fast as the consumer can accept.
    uint64_t messages_per_second = 100000;

    // Used only when instruments is empty.  These are explicitly synthetic
    // six-character identifiers, not a claim about currently listed symbols.
    uint32_t shanghai_instruments = 2500;
    uint32_t shenzhen_instruments = 2500;
    uint32_t derivatives_per_market = 64;
    bool include_derivatives = true;

    uint32_t book_depth = 10;
    uint32_t orders_per_level = 4;
    uint32_t callback_threads = 4;
    uint32_t callback_queue_capacity = 65536;
    BackpressurePolicy backpressure = BackpressurePolicy::Block;

    ClockMode clock_mode = ClockMode::Realtime;
    uint32_t max_realtime_lag_ms = 5;
    // Deterministic Gregorian weekday used only by SimulatedTradingDay.
    // This is a synthetic test date, not an exchange holiday-calendar claim.
    uint32_t simulated_start_date = 20260105; // yyyymmdd (Monday)
    uint32_t simulated_start_time = 93000000; // hhmmssmmm
    uint32_t simulated_min_step_ms = 0;
    uint32_t simulated_max_step_ms = 3;

    // These values are mock-local tokens because the supplied SDK does not
    // define the exchange code tables for these fields.
    std::string trading_phase_code = "T";
    int32_t mock_order_type = 0;
    int32_t mock_exec_type = 0;

    // When non-empty this exact universe replaces all synthetic instruments.
    std::vector<Instrument> instruments;
};

struct MessageKey {
    uint8_t service_id = MDLSID_UNDEFINED;
    uint16_t service_version = 0;
    uint16_t message_id = 0;
};

enum class MessageRole {
    Snapshot,
    Order,
    Trade
};

struct SupportedMessage {
    MessageKey key;
    MessageRole role = MessageRole::Snapshot;
    std::string cpp_type;
};

struct Statistics {
    uint64_t generated = 0;
    uint64_t delivered = 0;
    uint64_t filtered = 0;
    uint64_t dropped = 0;
    uint64_t callback_errors = 0;
    uint64_t queue_high_watermark = 0;
    uint64_t active_subscribers = 0;
};

// Returns an empty string when valid.  No filesystem or network access occurs.
std::string ValidateConfig(const Config& config);

// Builds a deterministic, clearly synthetic full-market-scale universe for
// stress tests.  Callers that need an authoritative security master should
// populate Config::instruments from their own dated source instead.
std::vector<Instrument> MakeSyntheticUniverse(
    uint32_t shanghai_count,
    uint32_t shenzhen_count,
    uint32_t derivatives_per_market,
    bool include_derivatives = true);

// Exact SID/version/MID combinations generated by this implementation.
const std::vector<SupportedMessage>& SupportedMessages();

// Convenience equivalent to AddSubscription() for every entry returned by
// SupportedMessages().  Fine-grained SubcribeMessage<T>() remains available.
void SubscribeAll(Subscriber* subscriber);

// Drop-in interface: after this one factory change, callers use the SDK's
// IOManager/Subscriber/MessageHandler/MDLMessage interfaces and payload types.
IOManagerPtr CreateIOManager(const Config& config = Config());

bool IsMockIOManager(const IOManager* manager);
Statistics GetStatistics(const IOManager* manager);

} // namespace mock
} // namespace mdl
} // namespace datayes
