"""Low-latency, read-only Python client for L2Flow realtime market data."""

from .batch import LatestBatch, TickBatch, TickColumnBatch
from .client import (
    DEFAULT_STALE_AFTER_NS,
    L2FlowClient,
    TickCursor,
)
from .factor import FactorResult, TickFactorRunner
from .models import (
    Aggressor,
    BestQueue,
    BookLevel,
    ClientClosedError,
    CommonRecord,
    DecimalValue,
    InconsistentReadError,
    Instrument,
    KLine,
    L2FlowRealtimeError,
    LatestResult,
    LatestStatus,
    Market,
    MarketEventKind,
    NativeReaderError,
    OptionalDependencyError,
    OrderType,
    ProtocolError,
    QuantityValue,
    ServerState,
    SessionIdentity,
    SessionInfo,
    Side,
    Snapshot,
    StaleSessionError,
    Tick,
    TickAction,
    TickOverrunError,
    TradingPhase,
    UnavailableError,
    WireFormatError,
)


def connect(control_socket_path, **kwargs) -> L2FlowClient:
    return L2FlowClient.connect(control_socket_path, **kwargs)


__all__ = [
    "Aggressor",
    "BestQueue",
    "BookLevel",
    "ClientClosedError",
    "CommonRecord",
    "DEFAULT_STALE_AFTER_NS",
    "DecimalValue",
    "FactorResult",
    "InconsistentReadError",
    "Instrument",
    "KLine",
    "L2FlowClient",
    "L2FlowRealtimeError",
    "LatestBatch",
    "LatestResult",
    "LatestStatus",
    "Market",
    "MarketEventKind",
    "NativeReaderError",
    "OptionalDependencyError",
    "OrderType",
    "ProtocolError",
    "QuantityValue",
    "ServerState",
    "SessionIdentity",
    "SessionInfo",
    "Side",
    "Snapshot",
    "StaleSessionError",
    "Tick",
    "TickAction",
    "TickBatch",
    "TickColumnBatch",
    "TickCursor",
    "TickFactorRunner",
    "TickOverrunError",
    "TradingPhase",
    "UnavailableError",
    "WireFormatError",
    "connect",
]
