"""Low-latency, read-only Python client for L2Flow realtime market data."""

from .batch import LatestBatch, TickBatch, TickColumnBatch
from .checkpoint import InstrumentTickDeltaCheckpoint
from .client import (
    DEFAULT_STALE_AFTER_NS,
    L2FlowClient,
    TickCursor,
)
from .factor import FactorResult, TickFactorRunner
from .history import (
    HistoryCursor,
    HistoryGeneration,
    HistoryInternalFailureError,
    HistoryNotFoundError,
    HistoryPage,
    HistoryRecord,
    HistoryResourceExhaustedError,
    connect_history,
    open_history_cursor,
)
from .instrument_delta import (
    DEFAULT_INSTRUMENT_TICK_DELTA_PAGE_RECORDS,
    InstrumentTickDeltaBaseKind,
    InstrumentTickDeltaCheckpointMismatchError,
    InstrumentTickDeltaCheckpointUnavailableError,
    InstrumentTickDeltaCursor,
    InstrumentTickDeltaGeneration,
    InstrumentTickDeltaInternalFailureError,
    InstrumentTickDeltaMetadata,
    InstrumentTickDeltaNotFoundError,
    InstrumentTickDeltaPage,
    InstrumentTickDeltaResourceExhaustedError,
    InstrumentTickDeltaSession,
    open_instrument_tick_delta_session,
)
from .models import (
    Aggressor,
    BestQueue,
    BookLevel,
    ClientClosedError,
    CommonRecord,
    DecimalValue,
    InconsistentReadError,
    Instrument,
    InstrumentKey,
    InstrumentLookupResult,
    InstrumentLookupStatus,
    KLine,
    L2FlowRealtimeError,
    LatestResult,
    LatestStatus,
    Market,
    MarketEventKind,
    NativeReaderError,
    OptionalDependencyError,
    OrderType,
    ProtocolError,
    QuantityValue,
    ServerState,
    SessionIdentity,
    SessionInfo,
    Side,
    Snapshot,
    StaleSessionError,
    Tick,
    TickAction,
    TickProjectionFlag,
    TickOverrunError,
    TradingPhase,
    UnavailableError,
    WireFormatError,
)
from .rolling import (
    InstrumentTickColumns,
    InstrumentTickRollingCommit,
    InstrumentTickRollingFactor,
    InstrumentTickRollingGeneration,
    InstrumentTickRollingState,
    InstrumentTickRollingStore,
    InstrumentTickRollingTransaction,
    InstrumentTickRollingUpdate,
    InstrumentTickRollingWindow,
)


def connect(control_socket_path, **kwargs) -> L2FlowClient:
    return L2FlowClient.connect(control_socket_path, **kwargs)


__all__ = [
    "Aggressor",
    "BestQueue",
    "BookLevel",
    "ClientClosedError",
    "CommonRecord",
    "DEFAULT_STALE_AFTER_NS",
    "DEFAULT_INSTRUMENT_TICK_DELTA_PAGE_RECORDS",
    "DecimalValue",
    "FactorResult",
    "HistoryCursor",
    "HistoryGeneration",
    "HistoryInternalFailureError",
    "HistoryNotFoundError",
    "HistoryPage",
    "HistoryRecord",
    "HistoryResourceExhaustedError",
    "InconsistentReadError",
    "Instrument",
    "InstrumentKey",
    "InstrumentLookupResult",
    "InstrumentLookupStatus",
    "InstrumentTickDeltaBaseKind",
    "InstrumentTickDeltaCheckpoint",
    "InstrumentTickDeltaCheckpointMismatchError",
    "InstrumentTickDeltaCheckpointUnavailableError",
    "InstrumentTickDeltaCursor",
    "InstrumentTickDeltaGeneration",
    "InstrumentTickDeltaInternalFailureError",
    "InstrumentTickDeltaMetadata",
    "InstrumentTickDeltaNotFoundError",
    "InstrumentTickDeltaPage",
    "InstrumentTickDeltaResourceExhaustedError",
    "InstrumentTickDeltaSession",
    "InstrumentTickColumns",
    "InstrumentTickRollingCommit",
    "InstrumentTickRollingFactor",
    "InstrumentTickRollingGeneration",
    "InstrumentTickRollingState",
    "InstrumentTickRollingStore",
    "InstrumentTickRollingTransaction",
    "InstrumentTickRollingUpdate",
    "InstrumentTickRollingWindow",
    "KLine",
    "L2FlowClient",
    "L2FlowRealtimeError",
    "LatestBatch",
    "LatestResult",
    "LatestStatus",
    "Market",
    "MarketEventKind",
    "NativeReaderError",
    "OptionalDependencyError",
    "OrderType",
    "ProtocolError",
    "QuantityValue",
    "ServerState",
    "SessionIdentity",
    "SessionInfo",
    "Side",
    "Snapshot",
    "StaleSessionError",
    "Tick",
    "TickAction",
    "TickProjectionFlag",
    "TickBatch",
    "TickColumnBatch",
    "TickCursor",
    "TickFactorRunner",
    "TickOverrunError",
    "TradingPhase",
    "UnavailableError",
    "WireFormatError",
    "connect",
    "connect_history",
    "open_history_cursor",
    "open_instrument_tick_delta_session",
]
